#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI-1 --mode 1920x1080 --pos -1920x0 --rotate normal


bspc monitor eDP-1 -d I III V VII IX
bspc monitor HDMI-1 -d II IV VI VIII X

~/.config/polybar/launch.sh

bspc config border_width         7
bspc config window_gap          20

bspc config focused_border_color \#ffb86c
bspc config normal_border_color \#ff79c6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill Downloads/wp6889832.jpg

xinput set-prop 10 334 1


picom

